# Generated by Django 4.2.10 on 2024-03-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatNewsAgency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
